import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { buildIr } from "jsr:@disjukr/bdl@0.8.3/io/ir";
import type {
  BdlIr,
  Custom,
  Def,
  Enum,
  Struct,
  StructField,
  Type as IrType,
  Union,
} from "jsr:@disjukr/bdl@0.8.3/ir";

const configPath = "bdl.yaml";
const outputPath = "schema/generated/nurijip.d.ts";

const localName = (typePath: string) => typePath.split(".").at(-1)!;
const prop = (name: string) =>
  /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);

function renderType(type: IrType): string {
  if (type.type === "Dictionary") {
    return `Record<${localName(type.keyTypePath)}, ${localName(type.valueTypePath)}>`;
  }
  return `${localName(type.valueTypePath)}${type.type === "Array" ? "[]" : ""}`;
}

const renderField = (field: StructField) =>
  `${prop(field.name)}${field.optional ? "?" : ""}: ${renderType(field.fieldType)}`;

function renderDefinition(definition: Def): string {
  if (definition.type === "Custom") {
    const def = definition as Custom;
    return `export type ${def.name} = ${renderType(def.originalType)};`;
  }
  if (definition.type === "Enum") {
    const def = definition as Enum;
    const items = def.items.map((item) => JSON.stringify(item.attributes.value ?? item.name));
    return `export type ${def.name} = ${items.join(" | ")};`;
  }
  if (definition.type === "Struct") {
    const def = definition as Struct;
    const fields = def.fields.map((field) => `  ${renderField(field)};`);
    return [`export interface ${def.name} {`, ...fields, "}"].join("\n");
  }
  const def = definition as Union;
  const discriminator = def.attributes.discriminator ?? "type";
  const variants = def.items.map((item) => {
    const fields = [
      `${prop(discriminator)}: ${JSON.stringify(item.name)}`,
      ...item.fields.map(renderField),
    ];
    return `  | { ${fields.join("; ")} }`;
  });
  return [`export type ${def.name} =`, `${variants.join("\n")};`].join("\n");
}

function getOrderedDefinitions(ir: BdlIr): Def[] {
  const seen = new Set();
  return Object.values(ir.modules)
    .flatMap((module) => module.defPaths)
    .filter((defPath) => {
      if (seen.has(defPath)) {
        return false;
      }
      seen.add(defPath);
      return true;
    })
    .map((defPath) => ir.defs[defPath]!);
}

function renderTypes(ir: BdlIr): string {
  return [
    "/* eslint-disable */",
    "// This file is generated by scripts/gen-ts.ts.",
    `// Source: ${configPath}`,
    "",
    getOrderedDefinitions(ir).map(renderDefinition).join("\n\n"),
    "",
  ].join("\n");
}

async function main() {
  const { ir } = await buildIr({
    config: configPath,
    standard: "conventional",
    omitFileUrl: true,
  });
  const output = renderTypes(ir);
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, output, "utf8");
  console.log(`wrote ${outputPath}`);
}

main().catch((error) => {
  console.error(error);
  Deno.exit(1);
});
